name: Clang

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: musicscience37/clang-ci:clang18

    steps:
    - uses: actions/checkout@v2

    - name: Build With Clang
      run: |
        cmake --preset clang-ninja
        cmake --build ./build/clang-ninja --config Release

    - name: Run Tests
      run: |
        ./build/clang-ninja/UtilyTest
        ./build/clang-ninja/UtilyBenchmark