name: Clang

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: musicscience37/clang-ci:clang18

    steps:
    - uses: actions/checkout@v2

    - name: Build With Clang
      run: |
        cmake --preset clang-ninja -DCMAKE_BUILD_TYPE=Release
        cmake --build ./build/clang-ninja --target UtilyTest --config Debug
        cmake --build ./build/clang-ninja --target UtilyBenchmark --config Release


    - name: Run Tests
      run: |
        ./build/clang-ninja/UtilyTest

    - name: Run Benchmarks  
      run: | 
        ./build/clang-ninja/UtilyBenchmark