name: GCC

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: musicscience37/gcc-ci:gcc13
    steps:
    - uses: actions/checkout@v2

    - name: Build With GCC
      run: |
        cmake --preset gcc-ninja -DCMAKE_BUILD_TYPE=Release 
        cmake --build ./build/gcc-ninja --target UtilyTest --config Debug
        cmake --build ./build/gcc-ninja --target UtilyBenchmark --config Release

    - name: Run Tests
      run: |
        ./build/gcc-ninja/UtilyTest

    - name: Run Benchmarks  
      run: | 
        ./build/gcc-ninja/UtilyBenchmark